### ISSUE TITLE
Multiline comments cause Fatal error:  Nesting level too deep - recursive dependency

### ISSUE THREAD

**Issue by loota** [iangreenleaf/Scisr#35]
This seems to not happen on version 5.2.11 of PHP. Sorry, I forgot to include the PHP version and other possibly useful data on the machine that produced the error. I'll try to post those on Monday.

**\* Test file Foo.php

<pre>
<?php
/*
*/ 
</pre>

**\* Command

<code>php scisr.php rename-class Foo Bar Foo.php  </code>

**\* Output

<pre>
PHP Fatal error:  Nesting level too deep - recursive dependency? in /home/heikki/ohjelmat/Scisr/Operations/AbstractTrackVariableTypeOperation.php on line 24

Fatal error: Nesting level too deep - recursive dependency? in /home/heikki/ohjelmat/Scisr/Operations/AbstractTrackVariableTypeOperation.php on line 24
</pre>

**Comment by iangreenleaf** [comment]
In addition to the PHP version, I'd be interested to hear if some of the unit tests fail on the machine that is having this problem. If you can install PHPUnit, you can run all the tests with
    cd Scisr/tests;
    phpunit .;

**Comment by loota** [comment]
It was 5.2.0, so I'm not sure if anyone would even want to support that old version. The PHP/PHPunit on that box didn't understand that command syntax with the dot and a semicolon as argument. When I tried to run some of the tests a lot of them failed.

**Comment by iangreenleaf** [comment]
Yeah, that's probably a bit on the old side. I'm hoping to support all the reasonably up-to-date versions of PHP 5, but for the 5.2.x branch I think that's more like 5.2.12 or 5.2.13.

If you do come up with a clean patch for this, go ahead and shoot it back to me.
