### ISSUE TITLE
Wish for new operation: Split file with many classes into separate files

### ISSUE THREAD

**Issue by tarjei** [iangreenleaf/Scisr#37]
Hi, have you considered writing a refactoring for splitting one file with many classes into a set of files with one class in each?

**Comment by iangreenleaf** [comment]
An interesting idea; no, I hadn't considered this before. Probably wouldn't be too hard - just need to add some logic for file creation.

**Comment by tarjei** [comment]
Would you mind giving an outline of how this could be implemented? I need this for a biggish conversion job so if you gave me some tips on implementing this I could contribute the code back.

**Comment by iangreenleaf** [comment]
Sure. You'll want to write an Operation class to do the work. Look at the other classes in that folder for some guidance (RenameClass should be a good place to start). Operations are closely based on [PHP_Codesniffer sniffs](http://pear.php.net/manual/en/package.php.php-codesniffer.coding-standard-tutorial.php) (Scisr is powered by the Codesniffer engine). That will make it easy to find the the class declaration and the end of the scope, and then you just have to figure out how to cut the code out of the current file and paste it into a new one. I've got a delayed-edit thing in Scisr_File, but you might need to add to it for this task.

You'll also want to add a method to ScisrRunner to load up the operation, and some code in CLI to take the appropriate command from the command line.

I think that's everything - if you get stuck let me know.
