### ISSUE TITLE
Unit tests fail with current PHPUnit

### ISSUE THREAD

**Issue by kdambekalns** [iangreenleaf/Scisr#42]
Expecting the bare Exception class is no longer allowed in PHPUnit (and using it eliminates fine-grained catch use).

**Comment by kdambekalns** [comment]
See https://github.com/iangreenleaf/Scisr/pull/43 for a fix.

**Comment by iangreenleaf** [comment]
Thanks! You also inspired me to set the project up on Travis: http://travis-ci.org/#!/iangreenleaf/Scisr

**Comment by kdambekalns** [comment]
Nice to see such blazing fast reactions! Thanks! :)
