### ISSUE TITLE
Use in commercial apps

### ISSUE THREAD

**Issue by mtangoo** [iangreenleaf/Scisr#45]
I'm not a lawyer but would be happy to incorporate this project in my editor. I expect to change nothing and if I fix anything I will happily contribute back. 

Is that allowed or will be illegal?

**Comment by iangreenleaf** [comment]
Hi @mtangoo, I'm glad you're interested in the project! It's [licensed under the GPLv3](https://github.com/iangreenleaf/Scisr/blob/master/LICENSE). In short, this means that you are welcome to use and modify the code, and to charge for it if you wish. However, if you distribute a program that uses this code, you will be required to make your code available under the GPLv3 as well. Will this work for your project?
